[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
serde = "1.0.188"
serde_json = "1.0.107"
shuttle-axum = "0.27.0"
shuttle-runtime = "0.27.0"
tokio = "1.28.2"
